name: Save Feedback

on:
  issues:
    types: [opened]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read issue body
        run: echo '${{ github.event.issue.body }}' > new-feedback.json

      - name: Merge feedback into feedback.json
        run: |
          echo "Merging feedback..."
          jq -s '.[0] + [.[1]]' feedback.json new-feedback.json > merged.json
          mv merged.json feedback.json

      - name: Commit feedback.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "New feedback added"
          branch: main
